### ISSUE TITLE
Camera preview not working 

### ISSUE THREAD

**Issue by danigamba** [genicam/harvesters_gui#11]
**Describe the bug**
The camera preview remains black and does not show frames captured from the camera.

**To Reproduce**
- Install harvesters-gui from pypi
- Run the example script

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS (both with Gnome and Xfce)
 - Python 3.6.8

I tryed different verstions of PyQt and VisPy but seems like anything is working.
I can correctly acquire frames from the harvesters core example.

Using a Teledyne Dalsa Genie Nano

**Comment by kazunarikudo** [comment]
Hi Daniele,

Thank you for your report and for trying out Harvester!

One question: Which version of VisPy did you try to use with Harvester GUI? I think I have not specified VisPy version so you would get the latest version. However, I have just noticed they have already started to release on the 0.6 line that I had never tried before. Yeah, you might have confirmed Harvester GUI failed to work with a 0.5 but it's okay, we would nail it soon or later.

Best regards,
Kazunari

**Comment by danigamba** [comment]
Hi Kazunari,
thank you for the response.

I tryed
 - vispy 0.5.3, black screen
 - vispy 0.4.0, TypeError: message_handler() takes 2 positional arguments but 3 were given
 - vispy 0.6.2, black screen

In my current setup I have installed
 - harvesters 0.2.13
 - harvesters-gui 0.2.5
 - pyqt 5.13.2

If you have a working setup can you please tell me which version are currently working? I'm willing to help updating the code if necessary.

Thank you,
Daniele

**Comment by kazunarikudo** [comment]
Sorry for the delay. I have just confirmed the issue and the root cause is coming from the change made on Harvester version 0.2.13. I will fix the issue later. Thank you for your patience.

**Comment by kazunarikudo** [comment]
Sorry having kept you waiting for such long. I have just released version 0.3 that fixes the issue. Please let me know if it does not work for you. /Kazunari
