### ISSUE TITLE
Crash when click start acquisition

### ISSUE THREAD

**Issue by PLICHET** [genicam/harvesters_gui#21]
**Describe the bug**
Hello, GUI Crash with error message

**To Reproduce**
Click to start acquisition

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/11979923/96175404-25602380-0f2b-11eb-8230-1f7e8cdc93fa.png)

**Desktop (please complete the following information):**
Windows 10 

**Smartphone (please complete the following information):**
 - Device: [e.g. GALAXY S7]
 - OS: [ANDROID]
 - Browser [Chrome]

**Comment by kazunarikudo** [comment]
@Eddi-z @PLICHET Hi, I have just pushed the fix into the master. I would appreciate if you could tell me the outcome. Thanks, Kazunari.
