### ISSUE TITLE
Cannot select RGB in settings and weird grid on image

### ISSUE THREAD

**Issue by TrinhNC** [genicam/harvesters_gui#25]
**Describe the bug**
I'm using harvester GUI with an IDS camera (UI-3280P-C-HQ) which is a color camera, but in the setting I can only see Mono and Bayer Modes.
![image](https://user-images.githubusercontent.com/19979949/191941592-90394790-df54-43be-8be3-b25f3d455929.png)

The image I got in the GUI is monochrome and beside there is a weird grids as well.
![image](https://user-images.githubusercontent.com/19979949/191941356-05238a44-4e42-413a-a1a9-69f9e6324505.png)

**To Reproduce**

**Expected behavior**
Should have option to select RGB mode and no grid on image.

**Desktop (please complete the following information):**
 - OS: Windows

Anyone has the same experience? any solutions?

**Comment by kazunarikudo** [comment]
@TrinhNC Hi, thank you for trying out Harvester. To resolve the issue you are facing, please read [this ticket](https://github.com/genicam/harvesters/issues/366). Thanks, Kazunari.

**Comment by TrinhNC** [comment]
Solved! [Link]((https://github.com/genicam/harvesters/issues/366#issuecomment-1266433292))
